parameters:
    es.logging.path: %kernel.logs_dir%/elasticsearch_%kernel.environment%.log
    es.manager.class: ONGR\ElasticsearchBundle\Service\Manager
    es.repository.class: ONGR\ElasticsearchBundle\Service\Repository
    es.manager_factory.class: ONGR\ElasticsearchBundle\Service\ManagerFactory
    es.export.class: ONGR\ElasticsearchBundle\Service\ExportService
    es.import.class: ONGR\ElasticsearchBundle\Service\ImportService
    es.client.index_suffix_finder.class: ONGR\ElasticsearchBundle\Service\IndexSuffixFinder
    es.document_finder.class: ONGR\ElasticsearchBundle\Mapping\DocumentFinder
    es.document_parser.class: ONGR\ElasticsearchBundle\Mapping\DocumentParser
    es.metadata_collector.class: ONGR\ElasticsearchBundle\Mapping\MetadataCollector
    es.logger.collection_handler.class: ONGR\ElasticsearchBundle\Profiler\Handler\CollectionHandler
    es.profiler.class: ONGR\ElasticsearchBundle\Profiler\ElasticsearchProfiler
    es.doctrine.filesystem_cache.class: Doctrine\Common\Cache\FilesystemCache
    es.result_converter.class: ONGR\ElasticsearchBundle\Result\Converter
    es.profiler.template: ONGRElasticsearchBundle:Profiler:profiler.html.twig

services:
    es.export:
        class: %es.export.class%

    es.import:
        class: %es.import.class%

    es.client.index_suffix_finder:
        class: %es.client.index_suffix_finder.class%

    es.cache_engine:
        class: %es.doctrine.filesystem_cache.class%
        arguments: ["%kernel.cache_dir%/ongr", ".ongr.data"]

    annotations.cached_reader:
        class: %annotations.cached_reader.class%
        arguments: [@annotations.reader, @es.cache_engine, %kernel.debug%]

    es.document_finder:
        class: %es.document_finder.class%
        arguments: [%kernel.bundles%]
        public: false

    es.document_parser:
        class: %es.document_parser.class%
        arguments: [@annotations.cached_reader, @es.document_finder]
        public: false

    es.metadata_collector:
        class: %es.metadata_collector.class%
        arguments: [@es.document_finder, @es.document_parser, @es.cache_engine]

    es.logger.collection_handler:
        class: %es.logger.collection_handler.class%
        public: false

    es.logger.ongr:
        class: %monolog.logger.class%
        arguments: ['ongr']
        calls:
            - [pushHandler, [@es.logger.collection_handler]]

    es.profiler:
        class: %es.profiler.class%
        calls:
            - [setManagers, [%es.managers%]]
            - [addLogger, [@es.logger.ongr]]
        tags:
            - {name: data_collector, template: %es.profiler.template%, id: ongr}

    es.result_converter:
        class: %es.result_converter.class%
        arguments: [@es.metadata_collector]

    es.manager_factory:
        class: %es.manager_factory.class%
        arguments: [@es.metadata_collector, @es.cache_engine, @es.result_converter]