language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - ELASTICSEARCH="1.5.2"
  - ELASTICSEARCH="1.6.2"
  - ELASTICSEARCH="1.7.2"

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
 - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb
 - sudo dpkg -i elasticsearch-${ELASTICSEARCH}.deb

install:
  - "echo 'script.disable_dynamic: false' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - "echo 'index.warmer.enabled: true' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo service elasticsearch restart

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/ ./

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e47479feba5ba8dc47
    on_success: change
    on_start: never
