sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - elasticsearch

matrix:
  allow_failures:
    - php: hhvm

install:
  - "echo 'script.disable_dynamic: false' | tee -a /etc/elasticsearch/elasticsearch.yml"
  - "echo 'index.warmer.enabled: true' | tee -a /etc/elasticsearch/elasticsearch.yml"
  - service elasticsearch restart

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/ ./

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e47479feba5ba8dc47
    on_success: change
    on_start: never
