language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - ELASTICSEARCH="1.3.9"
  - ELASTICSEARCH="1.4.5"
  - ELASTICSEARCH="1.5.2"
  - ELASTICSEARCH="1.6.0"

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_install:
 - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb
 - sudo dpkg -i elasticsearch-${ELASTICSEARCH}.deb

install:
  - "echo 'script.disable_dynamic: false' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - "echo 'index.warmer.enabled: true' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo service elasticsearch restart
  - sudo pip install -q sphinx
  - wget -q -O conf.py https://raw.githubusercontent.com/ongr-io/docs-aggregator/master/source/conf-travis.py

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/ ./
  - sphinx-build -nWq -b html -c . Resources/doc _build/html

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && wget --post-data="" -q -O /dev/null http://readthedocs.org/build/ongr'
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  slack: ongr:oyJ6inOcsttTBsnkuHV6dWbT
