language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - elasticsearch
env:
  - ELASTICSEARCH="1.3.6"
  - ELASTICSEARCH="1.4.1"
before_install:
 - sudo apt-get purge elasticsearch
 - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb
 - sudo dpkg -i elasticsearch-${ELASTICSEARCH}.deb
install:
  - "echo 'script.disable_dynamic: false' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo service elasticsearch restart
before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover